export const tasksData = [
    {
        id:1,
        title:"Create a new component",
        description:"Create a new React component from scratch, including its HTML, CSS, and JavaScript files.",
        priority:"Low",
        status:"Pending",
        dueDate:"2025-03-21",
    },
    {
        id:2,
        title:"Fix bug in login page",
        description:"Fix bug on the login page where the password input field does not show the correct character count.",
        priority:"High",
        status:"In-Progress",
        dueDate:"2023-05-03",
    },
    {
        id:3,
        title:"Add new feature to dashboard",
        description:"Add a new feature to the dashboard that shows the total number of tasks completed by the user.",
        priority:"Medium",
        status:"Completed",
        dueDate:"2023-05-05",
    },
    {
        id:4,
        title:"Write unit test for login page",
        description:"Write unit tests for the login page to ensure that the login functionality works correctly.",
        priority:"Low",
        status:"Pending",
        dueDate:"2023-05-02",
    },
    {
        id:5,
        title:"Update the UI of the homepage",
        description:"Update the UI of the homepage to make it look more visually appealing.",
        priority:"Medium",
        status:"In-Progress",
        dueDate:"2023-05-07",
    },
    {
        id:6,
        title:"Add social media sharing buttons",
        description:"Add social media sharing buttons to the blog posts to allow users to share them on their social media profiles.",
        priority:"Low",
        status:"Completed",
        dueDate:"2023-05-04",
    },
    {
        id:7,
        title:"Improve performance of the website",
        description:"Improve the performance of the website by optimizing the images, minifying the code, and using a content delivery network (CDN).",
        priority:"High",
        status:"In-Progress",
        dueDate:"2023-05-08",
    },
    {
        id:8,
        title:"Add a new feature to the blog",
        description:"Add a new feature to the blog that allows users to subscribe to the blog and receive notifications when a new blog post is published.",
        priority:"Medium",
        status:"Pending",
        dueDate:"2023-05-06",
    },
    {
        id:9,
        title:"Fix bug in the navigation bar",
        description:"Fix bug in the navigation bar where the links are not clickable on mobile devices.",
        priority:"High",
        status:"In-Progress",
        dueDate:"2023-05-09",
    },
    {
        id:10,
        title:"Add a new page to the website",
        description:"Add a new page to the website that displays the company's contact information and allows users to submit a contact form.",
        priority:"Medium",
        status:"Completed",
        dueDate:"2023-05-10",
    },
]